### ISSUE TITLE
webgl平台 热更层调用非热更层函数并传递一个Action回调，但是在非热更层执行这个Action回调时会报错

### ISSUE THREAD

**Issue by Madnala98ljf** [Ourpalm/ILRuntime#770]
RuntimeError: function signature mismatch
    at VirtualFuncInvoker0<SafeFileHandle_t033FA6AAAC65F4BB25F4CBA9A242A58C95CD406E*>::Invoke(unsigned short, Il2CppObject*) (<anonymous>:wasm-function[1115]:0x74fa3)
    at dynCall_iii (<anonymous>:wasm-function[45931]:0xfac913)
    at invoke_iii (http://127.0.0.1:22978/game/webgl.wasm.framework.unityweb.js:19:249946)
    at Extensions_CreateInstance_mC85E3152FB5CD82957FC85A44A5AD2E74AFAB191 (<anonymous>:wasm-function[78866]:0x16ef31f)
    at dynCall_iiiii (<anonymous>:wasm-function[45894]:0xfac5d9)
    at invoke_iiiii (http://127.0.0.1:22978/game/webgl.wasm.framework.unityweb.js:19:250628)
    at ILRuntimeType_InitializeCustomAttribute_mA42BD8C946D0DDC24F2C3041927883F9F51690DF (<anonymous>:wasm-function[12885]:0x3f8b8f)
    at ILRuntimeType_GetCustomAttributes_m7E8AFD0F6D631E402D7ABC5877F3D5862682B676 (<anonymous>:wasm-function[75857]:0x163c586)
    at VirtualFuncInvoker2<bool, ValueTuple_1_tBFF71B8F72F9D197DB09CFE88F0C8C7FE97CEF75, ValueTuple_1_tBFF71B8F72F9D197DB09CFE88F0C8C7FE97CEF75>::Invoke(unsigned short, Il2CppObject*, ValueTuple_1_tBFF71B8F72F9D197DB09CFE88F0C8C7FE97CEF75, ValueTuple_1_tBFF71B8F72F9D197DB09CFE88F0C8C7FE97CEF75) (<anonymous>:wasm-function[1212]:0x79dfc)
    at System_Reflection_MemberInfo_Binding_GetCustomAttributes_1_mDEBDF86FD7916B2A624B7686D7B2C339C69202C7 (<anonymous>:wasm-function[58144]:0x12a6e75)(env: Windows,mg,1.06.2401020; lib: 3.2.5)

**Comment by BLC-SGTQ** [comment]
试试在项目里关掉静态批处理：）
